services:
    server_sf_yugioh:
        container_name: server_sf_yugioh
        image: 'nginx:1.25-alpine3.18'
        working_dir: /www
        volumes:
            - './symfony:/www/symfony'
            - './.docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro'
        ports:
            - '8080:80'

    php_sf_yugioh:
        container_name: php_sf_yugioh
        build: ./.docker/php
        working_dir: /www/symfony
        user: "1000:1000"
        volumes:
            - './symfony/:/www/symfony'
            - './.docker/php/php-ini-overrides.ini:/etc/php/8.2/fpm/conf.d/99-overrides.ini'

    mysql_sf_yugioh:
        image: mysql:8.0
        container_name: mysql_sf_yugioh
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: yugioh
            MYSQL_USER: Gadmin
            MYSQL_PASSWORD: test1234
        ports:
            - "3306:3306"
        volumes:
            - mysql_sf_yugioh:/var/lib/mysql
volumes:
    mysql_sf_yugioh: